# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-12 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommentTab',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('created_at', models.PositiveIntegerField()),
                ('updated_at', models.PositiveIntegerField()),
                ('event_id', models.PositiveIntegerField()),
                ('user_id', models.PositiveIntegerField()),
                ('content', models.CharField(max_length=10000)),
                ('status', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EventLikerTab',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('created_at', models.PositiveIntegerField()),
                ('updated_at', models.PositiveIntegerField()),
                ('user_id', models.PositiveIntegerField()),
                ('event_id', models.PositiveIntegerField()),
                ('status', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EventParticipantTab',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('created_at', models.PositiveIntegerField()),
                ('updated_at', models.PositiveIntegerField()),
                ('user_id', models.PositiveIntegerField()),
                ('event_id', models.PositiveIntegerField()),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='EventTab',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('created_at', models.PositiveIntegerField()),
                ('updated_at', models.PositiveIntegerField()),
                ('user_id', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=10000)),
                ('start_date', models.PositiveIntegerField()),
                ('end_date', models.PositiveIntegerField()),
                ('location_name', models.CharField(max_length=200)),
                ('location_x', models.DecimalField(decimal_places=8, max_digits=11)),
                ('location_y', models.DecimalField(decimal_places=8, max_digits=11)),
                ('status', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EventTagTab',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('tag_id', models.PositiveIntegerField()),
                ('event_id', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ImageTab',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('created_at', models.PositiveIntegerField()),
                ('updated_at', models.PositiveIntegerField()),
                ('path', models.CharField(max_length=100)),
                ('event_id', models.PositiveIntegerField()),
                ('status', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TagTab',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
