# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-12 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='eventtagtab',
            index=models.Index(fields=['tag_id'], name='idx_tag_id'),
        ),
        migrations.AddIndex(
            model_name='eventparticipanttab',
            index=models.Index(fields=['event_id'], name='idx_event_id'),
        ),
        migrations.AddIndex(
            model_name='commenttab',
            index=models.Index(fields=['event_id'], name='idx_event_id'),
        ),
        migrations.AddIndex(
            model_name='imagetab',
            index=models.Index(fields=['event_id'], name='idx_event_id'),
        ),
        migrations.AddIndex(
            model_name='eventlikertab',
            index=models.Index(fields=['event_id'], name='idx_event_id'),
        ),
    ]
