export const UserAction = {
  LOGIN: 'LOGIN',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  SIGNUP: 'SIGNUP',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  GET_PROFILE: 'GET_PROFILE',
  GET_PROFILE_SUCCESS: 'GET_PROFILE_SUCCESS',
  LOGOUT: 'LOGOUT',
  UPLOAD_IMAGE: 'UPLOAD_IMAGE',
};

export const EventAction = {
  SEARCH: 'SEARCH',
  SEARCH_SUCCESS: 'SEARCH_SUCCESS',
  GET_LIST: 'GET_LIST',
  GET_LIST_SUCCESS: 'GET_LIST_SUCCESS',
  GET_DETAIL: 'GET_DETAILS',
  GET_DETAIL_SUCCESS: 'GET_DETAILS_SUCCESS',
  CREATE_EVENT: 'CREATE_EVENT',
  UPDATE_EVENT: 'UPDATE_EVENT',
  ADD_IMAGE_TO_EVENT: 'ADD_IMAGE_TO_EVENT',
  ADD_IMAGE_TO_EVENT_SUCCESS: 'ADD_IMAGE_TO_EVENT_SUCCESS',
  UPDATE_IMAGE_STATUS: 'UPDATE_IMAGE_STATUS',
  UPDATE_IMAGE_STATUS_SUCCESS: 'UPDATE_IMAGE_STATUS_SUCCESS',
};