# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-12 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserTab',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('created_at', models.PositiveIntegerField()),
                ('updated_at', models.PositiveIntegerField()),
                ('username', models.CharField(max_length=20)),
                ('fullname', models.CharField(max_length=20)),
                ('sex', models.SmallIntegerField()),
                ('role', models.SmallIntegerField()),
                ('password_hash', models.CharField(max_length=200)),
                ('password_salt', models.CharField(max_length=200)),
            ],
        ),
    ]
